### ISSUE TITLE
네이버쇼핑 통합구성요소 설치 후 구성 버튼을 눌렀을때 제대로 구성이 되지 않습니다.

### ISSUE THREAD

**Issue by saya6k** [oukene/naver_shopping#1]
올바른 권한(검색, WEB - $HOMEASSISTANT_WEB_EXTERNAL)을 가진 api client_id와 client_secret을 입력해 설치까지 가능합니다.

그 이후 검색 옵션 설정을 위해 통합구성요소 창에서 구성 버튼을 눌렀을 때 다음과 같은 에러창이 뜨면서 진행이 되지 않습니다.

<img width="559" alt="스크린샷 2023-05-29 13 33 25" src="https://github.com/oukene/naver_shopping/assets/63517312/6ad9f691-1515-4b07-b1e2-e3c21a4e1741">

로그입니다.
`2023-05-29 13:32:13.498 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 218, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 243, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/naver_shopping/config_flow.py", line 109, in async_step_init
    entity_registry = await homeassistant.helpers.entity_registry.async_get(self.hass)
TypeError: object EntityRegistry can't be used in 'await' expression
`

**Comment by oukene** [comment]
수정되었으니 확인해보세요

**Comment by saya6k** [comment]
해결되었습니다. 감사합니다.
